Feature: option in change custom notice text
AppSero/client pull request #17
Opened 2022-06-14 12:22 UTC by anisAronno

2022-06-15 04:43 UTC, tareq1988 commented
You've changed the coding convention from WordPress standard to PSR standard, which is not ideal for this library and has been skipped from the beginning. So revert all the changes and commit again with fixes.

2022-06-15 04:43 UTC, tareq1988 commented
You've changed the coding convention from WordPress standard to PSR standard, which is not ideal for this library and has been skipped from the beginning. So revert all the changes and commit again with fixes.

2022-06-15 05:00 UTC, saiftheboss7 commented
@anis3139  fix and give PR again

2022-06-15 07:06 UTC, anis3139 commented
> You've changed the coding convention from WordPress standard to PSR standard, which is not ideal for this library and has been skipped from the beginning. So revert all the changes and commit again with fixes.

I hope solved WordPress standard coding issue. Please check..

2022-06-24 09:30 UTC, tareq1988 requested changes

2022-06-24 09:30 UTC, tareq1988 commented on src/Insights.php
> +        $this->notice = sanitize_text_field($text);
It's not necessary to sanitize text here as it's not coming from the general untrusted users. Only when we are outputting, we need to escape the output with [escape functions](https://developer.wordpress.org/themes/theme-security/data-sanitization-escaping/#escaping-securing-output).

2022-06-30 10:46 UTC, tareq1988 requested changes

2022-06-30 10:46 UTC, tareq1988 commented on src/Insights.php
> +    public function notice(string $text='' ) {
Adding type-hinting here will require the user's to use PHP 7.0+. Remove it.

2022-06-30 10:52 UTC, merged