Fix: PHPCS Issues
Appsero/client pull request #25
Opened 2023-01-17 06:53 UTC by anis3139

2023-01-17 07:19 UTC, tareq1988 requested changes

2023-01-17 07:19 UTC, tareq1988 commented on src/Insights.php
> +            $server_data['software'] = sanitize_key( wp_unslash( $_SERVER['SERVER_SOFTWARE'] ) );
No need to sanitize here

2023-01-17 07:19 UTC, tareq1988 commented on src/Client.php
> +            $url, array(
Indentation problem here. I see the spaces have been replaced with tabs. Add a `.editorconfig` file in the root. [Example](https://github.com/weDevsOfficial/wp-user-frontend/blob/develop/.editorconfig)

```
root = true

[*]
indent_style = space
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

[{.jshintrc,*.json,*.yml}]
indent_style = space
indent_size = 2

[{*.txt,wp-config-sample.php}]
end_of_line = lf
```

2023-01-17 07:19 UTC, tareq1988 commented on src/Insights.php
> +            array(
Same indentation problem

2023-01-17 07:19 UTC, tareq1988 commented on src/Insights.php
> +			'active_plugins' => $active_plugins,
Indentation, replace tabs with spaces.

2023-01-17 11:39 UTC, anis3139 commented on src/Insights.php
> +            $server_data['software'] = sanitize_key( wp_unslash( $_SERVER['SERVER_SOFTWARE'] ) );
If I remove that, PHPCS gives an error.

2023-01-18 06:36 UTC, tareq1988 commented
There are still tab issues, [check here](https://github.com/Appsero/client/pull/25/files) and fix.

2023-03-01 08:31 UTC, saiftheboss7 commented
@tareq1988 bhai if all good, we can merge

2023-03-27 06:58 UTC, merged